name: Generate Snake

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite rodar manualmente na aba "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3
        with:
          # Nome do usuário do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # Onde os arquivos svg serão salvos
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
